// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdCTZSc-7g3Z_XZ45qHuYuLk49oYWlpes',
    appId: '1:819594970643:web:29f0123aeb4dc3ec30a1e6',
    messagingSenderId: '819594970643',
    projectId: 'learningflutterfire-f569f',
    authDomain: 'learningflutterfire-f569f.firebaseapp.com',
    storageBucket: 'learningflutterfire-f569f.appspot.com',
    measurementId: 'G-FVS1TNDRN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRlddSwQsICpVyu1svgLwYQFJkutvfYBs',
    appId: '1:819594970643:android:2aaa9a9a6c391f6930a1e6',
    messagingSenderId: '819594970643',
    projectId: 'learningflutterfire-f569f',
    storageBucket: 'learningflutterfire-f569f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM2z0_N5_HfFuAZDpDOGlUBKSAahp6pjQ',
    appId: '1:819594970643:ios:24265f6cd5d66fcc30a1e6',
    messagingSenderId: '819594970643',
    projectId: 'learningflutterfire-f569f',
    storageBucket: 'learningflutterfire-f569f.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM2z0_N5_HfFuAZDpDOGlUBKSAahp6pjQ',
    appId: '1:819594970643:ios:24265f6cd5d66fcc30a1e6',
    messagingSenderId: '819594970643',
    projectId: 'learningflutterfire-f569f',
    storageBucket: 'learningflutterfire-f569f.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdCTZSc-7g3Z_XZ45qHuYuLk49oYWlpes',
    appId: '1:819594970643:web:d6477d8b523bc4e730a1e6',
    messagingSenderId: '819594970643',
    projectId: 'learningflutterfire-f569f',
    authDomain: 'learningflutterfire-f569f.firebaseapp.com',
    storageBucket: 'learningflutterfire-f569f.appspot.com',
    measurementId: 'G-F2FFKZVHNS',
  );
}
